name: Deploy to Azure

on:
  push:
    branches:
      - next_version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install
      
      - name: Set PHP Version
        run: echo "export PHP_VERSION=8.2.9" >> $GITHUB_ENV
      
      - name: Configure PHP 
        run: |
          export PHP_VERSION=8.2.9
          oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 20 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dc3e60f633f885 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
      
      - name: Build
        run: npm run build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fernando-portfolio
          slot-name: production
          publish-profile: ${{ secrets.Azure_MY_Portfolio }}
