name: Deploy to Azure

on:
  push:
    branches:
      - next_version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install
       
      - name: Build
        run: npm run build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set PHP Version
        run: echo "export PHP_VERSION=8.2.9" >> $GITHUB_ENV

      - name: Update Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar update --with-all-dependencies

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: fernando-portfolio
          slot-name: production
          publish-profile: ${{ secrets.Azure_MY_Portfolio }}
          
