name: Deploy to Azure

on:
  push:
    branches:
      - next_version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.9

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          # Use PHP 8.2.9 for the build process
          export PHP_VERSION=8.2.9
          echo "export PHP_VERSION=$PHP_VERSION" >> $GITHUB_ENV
          
          # Run your build command, replace with your actual build command
          npm run build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fernando-portfolio
          slot-name: production
          publish-profile: ${{ secrets.Azure_MY_Portfolio }}
