# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fernando-portfolio

on:
  push:
    branches:
      - next_version
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          check-latest: true

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present 

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: my-portfolio
          path: release.zip

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: my-portfolio

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: Set up environment variable for Azure Web App
        run: echo "WEBSITES_PORT=3001" | tee -a $GITHUB_ENV

      - name: Install Nginx
        run: sudo apt-get install -y nginx

      - name: Configure Nginx
        run: |
          sudo rm /etc/nginx/sites-available/default
          sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
          server {
            listen 3000;
            server_name localhost;

            location / {
              proxy_pass http://localhost:3000; # Adjust the port based on your Node.js app
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
            }
          }
          EOL

      - name: Restart Nginx
        run: sudo systemctl restart nginx
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_90FE6096D2F84E9CBBD3FAF040136051 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FFC88A4CB8B4E78A9B38AA396C565D5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_76A2C93C52DD49B2ADBB1376FB0B5F35 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fernando-portfolio'
          slot-name: 'Production'
          package: .
          